# Generated by Django 5.1.2 on 2024-11-08 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='IN_PROGRESS', max_length=100, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='tripvoucher',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='tripinvoice',
            name='account_name',
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='resort_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sales_person',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='sales_person',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='attended_by',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tripvoucher',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='tripinvoice',
            name='meal_plan',
        ),
        migrations.DeleteModel(
            name='OwnResorts',
        ),
        migrations.DeleteModel(
            name='Resorts',
        ),
        migrations.DeleteModel(
            name='Script',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='resort_name',
        ),
        migrations.RemoveField(
            model_name='tripinvoice',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='tripvoucher',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='tripinvoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tripinvoice',
            name='sales_person',
        ),
        migrations.RemoveField(
            model_name='tripinvoicepayment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='tripvoucher',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tripvoucher',
            name='sales_person',
        ),
        migrations.RemoveField(
            model_name='tripvoucherpayment',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='sales_person',
        ),
        migrations.RemoveField(
            model_name='voucherpayment',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoicePayment',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='MealPlans',
        ),
        migrations.DeleteModel(
            name='Stay',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TripInvoice',
        ),
        migrations.DeleteModel(
            name='TripInvoicePayment',
        ),
        migrations.DeleteModel(
            name='TripVoucher',
        ),
        migrations.DeleteModel(
            name='TripVoucherPayment',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
        migrations.DeleteModel(
            name='VoucherPayment',
        ),
    ]
